### ISSUE TITLE
Poison Buyer: check bag amount of reagent before buying

### ISSUE THREAD

**Issue by cgoodroe** [rainfordays/Restocker#4]
Expected:
Restocker will check to see if you already have some of the poison reagents and buy the difference required to craft missing poisons.

Actual:
Restocker will buy all reagents every time you speak to the vendor, regardless of your current reagent count.

Steps to reproduce:
Talk to vendor, close vendor window, talk to vendor again.
Observe you have bought all the reagents twice.

PS. Love the addon, thanks for making it.

**Comment by rainfordays** [comment]
This is because of how when you buy in enough quantities it takes some time for the server to register your new items. Closing vendor and reopening in this "deadzone" where you've bought the items but they've yet to appear in your bags is what is causing this behaviour. 

Since this is something server sided I can't do anything about it except adding a timer. 

Which is too much trouble because all you have to do is stop closing and reopening the window and instead just wait for the items to get into your bags.

**Comment by cgoodroe** [comment]
@rainfordays I'm not sure that's true, as it was still happening 20+ minutes later

**Comment by rainfordays** [comment]
I just checked again and what you say is true. There is no checks made for the amount of reagents you already have either in bag or bank. Ill reopen this but it will probably be low priority for a while.

**Comment by rainfordays** [comment]
To remind myself: subtract current amount in storage after getting totals in poisons.lua after

**Comment by rainfordays** [comment]
Which would be prefferable, subtracting what you have in bags or what you have in total (bags and bank)?

**Comment by cgoodroe** [comment]
Personally I think just checking bags is enough.

**Comment by rainfordays** [comment]
This has now been added in the latest release.
